version: "3.9"

services:
  backend:
    container_name: cms-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-backend:latest
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: unless-stopped
