version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - CDN_BASE_URL=${CDN_BASE_URL}
