spring:
  application:
    name: 'backend'
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
    connect-retries: 5

logging:
  level:
    org.hibernate.sql: debug

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

bootstrap:
  admin:
    email: admin@gmail.com
    password: admin

springdoc:
  swagger-ui:
    enabled: true
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}

cdn:
  base-url: ${CDN_BASE_URL}